version: '3.8'

services:
  authelia:
    image: authelia/authelia:latest
    container_name: authelia
    environment:
      - TZ=Europe/Istanbul # Change to your timezone
    volumes:
      - ./config:/config
    ports:
      - 9091:9091
    restart: unless-stopped
