version: '3.8'

services:
  authelia:
    build: .
    container_name: authelia
    environment:
      - TZ=Europe/Istanbul # Change to your timezone
    ports:
      - 9091:9091
    restart: unless-stopped
